(use-modules (gnu)
             (gnu home)
             (gnu packages gnome)
             (gnu packages radio)
             (gnu services networking)
             (gnu system file-systems)
             (guix packages)
             (my-guix config)
             (my-guix home mods)
             (my-guix home mods base)
             (my-guix home services package-management)
             (my-guix mods)
             (my-guix mods desktop-environment)
             (my-guix mods hardware)
             (my-guix mods server)
             (my-guix systems al-laptop)
             (my-guix systems al-laptop alvin)
             (nongnu packages linux)
             (nongnu system linux-initrd))

(define system
  (modded-system
    (initial-os (modded-configuration-operating-system modded-operating-system))
    (initial-he (modded-configuration-home-environment modded-home-environment))))

(modded-system-guess-environment system)
