(use-modules (gnu)
             (gnu home)
             (gnu home services desktop)
             (gnu home services shepherd)
             (gnu home services sound)
             (gnu packages linux)
             (gnu services linux)
             (gnu services sddm)
             (gnu services web)
             (gnu services xorg)
             (gnu system)
             (gnu system file-systems)
             (gnu system privilege)
             (guix download)
             (guix git-download)
             (guix packages)
             (my-guix config)
             (my-guix home mods)
             (my-guix home mods base)
             (my-guix home services package-management)
             (my-guix mods)
             (my-guix mods base)
             (my-guix mods desktop-environment)
             (my-guix mods entertainment)
             (my-guix mods hardware)
             (my-guix mods server)
             (my-guix packages game-client)
             (my-guix packages mesa)
             (my-guix packages keyboard-center)
             (my-guix packages redlib)
             (my-guix services hardware)
             (my-guix systems al-pc)
             (my-guix systems al-pc alvin)
             (my-guix utils)
             (nongnu packages linux)
             ((nongnu packages nvidia) #:prefix nvidia:)
             ((nongnu services nvidia) #:prefix nvidia:)
             (nongnu system linux-initrd)
             (nonguix utils))

(define system
  (modded-system
    (initial-os (modded-configuration-operating-system modded-operating-system))
    (initial-he (modded-configuration-home-environment modded-home-environment))))

(modded-system-guess-environment system)
